import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { IonicModule, ModalController } from '@ionic/angular';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaintenancePart } from '../../../../utils/maintenancePart.service';
import { Catalog } from '../../../../utils/catalog.service';

@Component({
  selector: 'app-add-part-modal',
  templateUrl: './add-part-modal.component.html',
  styleUrls: ['./add-part-modal.component.scss'],
  imports: [
    CommonModule,
    IonicModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule
  ],
  standalone: true
})
export class AddPartModalComponent {
  @Input() unitOfMeasures: Catalog[] = [];
  @Output() partAdded = new EventEmitter<MaintenancePart>();
  
  partForm: FormGroup;

  constructor(
    private formBuilder: FormBuilder,
    private modalController: ModalController
  ) {
    this.partForm = this.createForm();
  }

  createForm(): FormGroup {
    return this.formBuilder.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      quantity: [1, [Validators.required, Validators.min(1)]],
      cost: [0, [Validators.required, Validators.min(0)]],
      unitOfMeasure: ['', [Validators.required]]
    });
  }

  onSubmit() {
    if (this.partForm.valid) {
      const partData = this.partForm.value;
      const part: MaintenancePart = {
        id: '', // Will be generated by server
        name: partData.name,
        quantity: partData.quantity,
        cost: partData.cost,
        unitOfMeasure: partData.unitOfMeasure,
        totalCost: partData.quantity * partData.cost
      };
      debugger
     // this.partAdded.emit(part);
      this.dismiss(part);
    }
  }

dismiss(part?: MaintenancePart) {
  this.modalController.dismiss(part);
}

  isFieldInvalid(fieldName: string): boolean {
    const field = this.partForm.get(fieldName);
    return !!(field && field.invalid && (field.dirty || field.touched));
  }

  getFieldError(fieldName: string): string {
    const field = this.partForm.get(fieldName);
    if (field && field.errors) {
      if (field.errors['required']) {
        return 'Este campo es requerido';
      }
      if (field.errors['minlength']) {
        return `Debe tener al menos ${field.errors['minlength'].requiredLength} caracteres`;
      }
      if (field.errors['min']) {
        return `El valor mínimo es ${field.errors['min'].min}`;
      }
    }
    return '';
  }
}

